GET http://localhost:5000/users

###
GET http://localhost:5000/users/4cac8053-1dcb-46e8-86fc-f01d4b4b4b9f

###
DELETE http://localhost:5000/users/4cac8053-1dcb-46e8-86fc-f01d4b4b4b9f

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Arsyad",
    "email": "arsyad@gmail.com",
    "password":"12345678",
    "confPassword": "12345678",
    "role":"murid"
}


###
GET http://localhost:5000/me


###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "malikabd@gmail.com",
    "password":"12345678"
}

### 
DELETE http://localhost:5000/logout

###
PATCH  http://localhost:5000/users/7706485e-f505-4a3e-b5f2-0c87ad6c2a0d
Content-Type: application/json

{
    "name":"Malik Abdullah",
    "email": "malikabd@gmail.com",
    "password":"12345678",
    "confPassword":"12345678",
    "role":"guru"
}

### 
POST http://localhost:5000/tasks
Content-Type: application/json

{
  "detail": "Buatlah Web seperti tokopedia, menggunakan html css only dan js vanila",
  "task": "e-comerse",
  "nilai": 90,
  "status": "pending",
  "userId": "cda88353-c1db-42f3-8ab2-80e03cc46e00"
}

###
PATCH  http://localhost:5000/tasks/19
Content-Type: application/json

{
  "detail": "buat tokped.",
  "task": "CRUD",
  "nilai": 90,
  "status": "completed"
}

### 
DELETE http://localhost:5000/tasks/7a9fdcc7-19c7-4478-b4ee-4caaf8107727


###
GET http://localhost:5000/tasks/19